### ISSUE TITLE
Support For Android APK

### ISSUE THREAD

**Issue by GSharma789** [superblaubeere27/obfuscator#41]
Please make this obfuscator in a way that it can be used to obfuscate apk at compile time in android studio like allatori doing . I found this obfuscator too good for jar files but now need such good protection for apk to . Hope you think on my request . Thanks

**Comment by Grennith** [comment]
Hi, since I hardly have the time to properly work on integrating it into this project, I'll just append [android_patch.txt](https://github.com/superblaubeere27/obfuscator/files/3292801/android_patch.txt)
 which is based on 589b70866c76c4c5121abdf76bf77700933665db 
What I changed was the way obfuscator reads in .class files. The usual way would be reading a .jar, obfuscating the .class files and packing it back up. Trivially, you can remove reading of a jar and simply read in a given directory recursively ;)

Keep in mind, that this is a quick and dirty patch, I "disabled" the tests along with it

Now that obfuscator can deal with directories you need to patch the obfuscation into the Gradle build process. I decided to run it right after compilation and before Proguard although superblaubeere27 recommends running Proguard only before obfuscator (it does take some bogus flow out of it making dynamic analysis a little easier I guess). If you want to run it after Proguard, you won't need to patch obfuscator, but you will need to find the correct jar being put together before being wrapped up to .dex. I guess it can work on `app/build/intermediates/transforms/proguard/release/0.jar` but I didn't test it tbh.

As for the Gradle bit of it (with the compiled/packaged obfuscator placed in the app folder obviously):
```
task androidObfuscateCodeRelease(type: Exec) {
    System.out.println("Obfuscating Java .class files (release)...\n")
    executable "/usr/bin/java"
    args = [
            "-jar",
            "app/obfuscator.jar",
            "-pathIn",
            "app/build/intermediates/javac/release/compileReleaseJavaWithJavac/classes/<whateverYourPackageNameStartsWith>",
            "-pathOut",
            "app/build/intermediates/javac/release/compileReleaseJavaWithJavac/classes/<whateverYourPackageNameStartsWith>"
    ]

}
```
and e.g. in the allprojects block:
```
tasks.whenTaskAdded { task ->
        if (task.name == 'generateJsonModelRelease') {
            task.dependsOn androidObfuscateCodeRelease
        }
    }```

**Comment by GSharma789** [comment]
thanks a lot sir

**Comment by 751643992** [comment]
> Please make this obfuscator in a way that it can be used to obfuscate apk at compile time in android studio like allatori doing . I found this obfuscator too good for jar files but now need such good protection for apk to . Hope you think on my request . Thanks
老哥，你在Android studio里面使用这个obfuscator保护android apk吗？

**Comment by superblaubeere27** [comment]
I think this is answered. If you still have questions, just comment
