### ISSUE TITLE
VirusTotale Found Java.Trojan.GenericGB.27004

### ISSUE THREAD

**Issue by SyaFR** [superblaubeere27/obfuscator#46]
I am check program and This VirusTotal Website found Java.Trojan.GenericGB.27004 ,Java/Kryptik.YO!tr ,Trojan.Java.GenericGB
Why found

**Comment by xLiquidCode** [comment]
False positive ;D
AntiVirus "can't read" obfuscated code, so it's detecting it as virus.

**Comment by cookiedragon234** [comment]
@SyaFR its open source lol. If your worried about a virus build the jar yourself.

**Comment by cookiedragon234** [comment]
Although I have to say it is quite worrying https://i.imgur.com/bUA8DwD.png

**Comment by superblaubeere27** [comment]
@SyaFR Well, I think this is caused by somebody used this program to create malware and an AV Company though that they could just blacklist the obfuscator. I tried reporting a False Positive but they didn't care about it. AntiVirus False Positives are not unusual. The obfuscator is open source, you can check it and you won't be able to find anything malicious. Anyways thank you for reporting this issue, even though I'm aware of it :D
